# This file was generated by GoReleaser. DO NOT EDIT.
cask "openx" do
  name "openx"
  desc "A cross-platform utility that makes command-line tools accessible from anywhere by creating symbolic links or wrapper scripts in your system's PATH"
  homepage "https://github.com/muthuishere/openx"
  version "0.2.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "openx"

  on_macos do
    on_intel do
      url "https://github.com/muthuishere/openx/releases/download/v#{version}/openx_#{version}_Darwin_x86_64.tar.gz"
      sha256 "606e61338a2e8ba9509355ad08487881fee3e1196955bebec84362fe1d8fc092"
    end
    on_arm do
      url "https://github.com/muthuishere/openx/releases/download/v#{version}/openx_#{version}_Darwin_arm64.tar.gz"
      sha256 "3a72acca3940153c8c94b475f93503434101a9b7793bc01ee7c024f8f1690457"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/muthuishere/openx/releases/download/v#{version}/openx_#{version}_Linux_x86_64.tar.gz"
      sha256 "524e7c6b8e59f2b41b72206cc18ed7a543daf9f2d277c1012ac84daf6c76efac"
    end
    on_arm do
      url "https://github.com/muthuishere/openx/releases/download/v#{version}/openx_#{version}_Linux_arm64.tar.gz"
      sha256 "c1aee31729ab0636aaad3109588789ee2eb4d216479a9d9c7f18fc9114bccadc"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/openx"]
    end
  end

  # No zap stanza required
end
