# This file was generated by GoReleaser. DO NOT EDIT.
cask "openx" do
  name "openx"
  desc "A cross-platform utility that makes command-line tools accessible from anywhere by creating symbolic links or wrapper scripts in your system's PATH"
  homepage "https://github.com/muthuishere/openx"
  version "0.1.9"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "openx"

  on_macos do
    on_intel do
      url "https://github.com/muthuishere/openx/releases/download/v#{version}/openx_#{version}_Darwin_x86_64.tar.gz"
      sha256 "2d167dc70a13c31001f71bc36cdd7293f4626efaf42c7f0a3107cdb7a3eeefee"
    end
    on_arm do
      url "https://github.com/muthuishere/openx/releases/download/v#{version}/openx_#{version}_Darwin_arm64.tar.gz"
      sha256 "effd630a11d4057acd8fe5b6a618f7db87719f230ed55cd606ea8747c58dc6b7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/muthuishere/openx/releases/download/v#{version}/openx_#{version}_Linux_x86_64.tar.gz"
      sha256 "89cc6262dfca67d812aa9e8af897510c122004a0805ce4aa1ac13efcb5c68309"
    end
    on_arm do
      url "https://github.com/muthuishere/openx/releases/download/v#{version}/openx_#{version}_Linux_arm64.tar.gz"
      sha256 "29da95f68408259d117a852da7ba8b6f3bd3e5364ef65de40855ce1d88eb3905"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/openx"]
    end
  end

  # No zap stanza required
end
